CREATE TABLE projects (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organization_id BIGINT UNSIGNED NOT NULL,
    project_key VARCHAR(40) NOT NULL,
    name VARCHAR(180) NOT NULL,
    description TEXT NULL,
    icon VARCHAR(255) NULL,
    status ENUM('active','archived','deleted') NOT NULL DEFAULT 'active',
    created_by_user_id BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_projects_org_key (organization_id, project_key),
    UNIQUE KEY uq_projects_id_org (id, organization_id),
    KEY idx_projects_org_status (organization_id, status, deleted_at),
    KEY idx_projects_created_by (created_by_user_id),
    FULLTEXT KEY ft_projects_name_description (name, description),
    CONSTRAINT fk_projects_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_projects_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE boards (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organization_id BIGINT UNSIGNED NOT NULL,
    project_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(120) NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_boards_id_org (id, organization_id),
    KEY idx_boards_project (project_id),
    KEY idx_boards_org_project (organization_id, project_id),
    CONSTRAINT fk_boards_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_boards_project_org FOREIGN KEY (project_id, organization_id) REFERENCES projects(id, organization_id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE board_columns (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organization_id BIGINT UNSIGNED NOT NULL,
    board_id BIGINT UNSIGNED NOT NULL,
    column_key VARCHAR(40) NOT NULL,
    title VARCHAR(100) NOT NULL,
    color VARCHAR(32) NULL,
    position INT NOT NULL DEFAULT 0,
    wip_limit INT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_board_columns_board_key (board_id, column_key),
    UNIQUE KEY uq_board_columns_id_org (id, organization_id),
    KEY idx_board_columns_org_board_position (organization_id, board_id, position),
    CONSTRAINT fk_board_columns_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_board_columns_board_org FOREIGN KEY (board_id, organization_id) REFERENCES boards(id, organization_id) ON DELETE CASCADE ON UPDATE CASCADE,
    CHECK (wip_limit IS NULL OR wip_limit >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE task_statuses (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organization_id BIGINT UNSIGNED NOT NULL,
    status_key VARCHAR(40) NOT NULL,
    name VARCHAR(80) NOT NULL,
    category ENUM('todo','in_progress','done','cancelled') NOT NULL DEFAULT 'todo',
    position INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_task_statuses_org_key (organization_id, status_key),
    KEY idx_task_statuses_org_category (organization_id, category),
    CONSTRAINT fk_task_statuses_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE tasks (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    organization_id BIGINT UNSIGNED NOT NULL,
    project_id BIGINT UNSIGNED NOT NULL,
    board_id BIGINT UNSIGNED NULL,
    column_id BIGINT UNSIGNED NULL,
    parent_task_id BIGINT UNSIGNED NULL,
    task_number BIGINT UNSIGNED NOT NULL,
    title VARCHAR(220) NOT NULL,
    description MEDIUMTEXT NULL,
    status_key VARCHAR(40) NOT NULL DEFAULT 'todo',
    priority ENUM('lowest','low','medium','high','highest') NOT NULL DEFAULT 'medium',
    start_date DATE NULL,
    due_date DATE NULL,
    completed_at DATETIME NULL,
    estimated_minutes INT UNSIGNED NULL,
    story_points DECIMAL(6,2) NULL,
    position DECIMAL(20,6) NOT NULL DEFAULT 0,
    created_by_user_id BIGINT UNSIGNED NULL,
    updated_by_user_id BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_tasks_org_number (organization_id, task_number),
    UNIQUE KEY uq_tasks_id_org (id, organization_id),
    KEY idx_tasks_org_project_status (organization_id, project_id, status_key, deleted_at),
    KEY idx_tasks_org_board_column (organization_id, board_id, column_id, position),
    KEY idx_tasks_due_date (organization_id, due_date),
    KEY idx_tasks_parent (parent_task_id),
    KEY idx_tasks_created_by (created_by_user_id),
    FULLTEXT KEY ft_tasks_title_description (title, description),
    CONSTRAINT fk_tasks_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_tasks_project_org FOREIGN KEY (project_id, organization_id) REFERENCES projects(id, organization_id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_tasks_board_org FOREIGN KEY (board_id, organization_id) REFERENCES boards(id, organization_id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_tasks_column_org FOREIGN KEY (column_id, organization_id) REFERENCES board_columns(id, organization_id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_tasks_parent FOREIGN KEY (parent_task_id) REFERENCES tasks(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_tasks_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_tasks_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CHECK (estimated_minutes IS NULL OR estimated_minutes >= 0),
    CHECK (story_points IS NULL OR story_points >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
