INSERT INTO permissions (name, description) VALUES
('organization:view','View organization details'),
('organization:update','Update organization settings'),
('member:invite','Invite users'),
('member:update','Update members'),
('member:remove','Remove members'),
('role:manage','Manage roles and permissions'),
('project:create','Create projects'),
('project:view','View projects'),
('project:update','Update projects'),
('project:delete','Delete projects'),
('task:create','Create tasks'),
('task:view','View tasks'),
('task:update','Update tasks'),
('task:delete','Delete tasks'),
('file:upload','Upload files'),
('file:view','View files'),
('file:delete','Delete files'),
('webhook:manage','Manage webhooks'),
('billing:manage','Manage billing'),
('apikey:manage','Manage API clients and keys'),
('audit:view','View audit logs'),
('chat:use','Use chat features')
ON CONFLICT (name) DO UPDATE SET
description = EXCLUDED.description;
