-- DEV ONLY. Do not run this in staging or production.
-- Password hash placeholder: replace with a bcrypt/argon2 hash generated by your application.
SET @dev_email = 'abraham@paladin.mx';
SET @dev_hash = '$2a$10$cw#FstN5*O6r5SC5sbpE+Sibpk?=Oy09uX8e5j1m';

INSERT INTO users (email, password_hash, full_name, is_active, is_platform_admin, email_verified_at)
VALUES (@dev_email, @dev_hash, 'Local Dev Admin', TRUE, TRUE, NOW())
ON DUPLICATE KEY UPDATE password_hash = VALUES(password_hash), is_active = TRUE, updated_at = NOW();

INSERT INTO organizations (name, slug, owner_user_id, status)
SELECT 'Local Dev Organization', 'local-dev', u.id, 'active'
FROM users u WHERE u.email = @dev_email
ON DUPLICATE KEY UPDATE updated_at = NOW();

INSERT IGNORE INTO member_roles (organization_id, member_id, role_id)
SELECT om.organization_id, om.id, r.id
FROM organization_members om
JOIN users u ON u.id = om.user_id
JOIN roles r ON r.organization_id IS NULL AND r.name = 'Owner'
WHERE u.email = @dev_email;
